# yaml-language-server: $schema=https://unpkg.com/syncpack/dist/schema.json

versionGroups:
  - label: "Use Workspace Protocol for Cross References"
    dependencies: ["$LOCAL"]
    dependencyTypes: ["!local"]
    pinVersion: "workspace:^"

sortFirst:
  # Information
  - name
  - version
  - description
  - author
  - license
  - keywords
  - private

  # Tooling
  - packageManager
  - scripts
  - workspaces

  # File Structure & API
  - type
  - bin
  - main
  - module
  - types
  - exports
  - files

sortAz:
  - bin
  - keywords
  - dependencies
  - devDependencies
  - peerDependencies
  - resolutions
