packageExtensions:
  "citlali@*":
    dependencies:
      "@citlali/workspace": "workspace:^"

  "@citlali/bundler@*":
    dependencies:
      "@citlali/workspace": "workspace:^"

  "@citlali/cli@*":
    dependencies:
      "@citlali/workspace": "workspace:^"

  "@citlali/core@*":
    dependencies:
      "@citlali/workspace": "workspace:^"

  "@citlali/runtime@*":
    dependencies:
      "@citlali/workspace": "workspace:^"

  "@citlali/utils@*":
    dependencies:
      "@citlali/workspace": "workspace:^"
